HRMS/HRMS/Models/EmployeeDetails.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace HRMS.Models
{
    public class EmployeeDetails
    {
        public string EmpId { get; set; }
       
        public String Emptype { get; set; }
        public string EmpFullName { get; set; }

        public DateTime EmpDateofBirth { get; set; }

        public string EmpGender { get; set; }

        public string EmpFathersName { get; set; }

        public string EmpMothersName { get; set; }

        public long EmpMobilenumber { get; set; }
      
        public string  EmpEmail { get; set; }

        public string EmpMartialStatus { get; set; }
        
        public string EmpPassword { get; set; }

        public string  EmpBloodGroup { get; set; }

        public string EmpPhysicallyChallenged { get; set; }

        public long EmpAadharCardNumaber { get; set; }

        public string  EmpPanCardNumber { get; set; }

        public string EmpStreetAddress { get; set; }

        public string EmpCity { get; set; }

        public string  EmpState { get; set; }

        public String EmpCountry { get; set; }

        public int EmpPinCode { get; set; }



    }
}

HRMS/HRMS/Models/EmployeeEmergencyDetails.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HRMS.Models
{
    public class EmployeeEmergencyDetails
    {
        public string   EmpId { get; set; }
        public string EmpGuadianName { get; set; }

        public string EmpGuardianEmail { get; set; }

        public long EmpGuardianMobileNumber { get; set; }

        public string EmpGuardianRelationshipType { get; set; }

    }
}

HRMS/HRMS/Models/EmployeeFormModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HRMS.Models
{
    public class EmployeeFormModel
    {
        public EmployeeDetails EmployeeDetail { get; set; }
        public EmployeeProfessionalDeatils  EmployeeProfessionalDeatil { get; set; }
        public EmployeeEmergencyDetails EmployeeEmergencyDetail { get; set; }
        
    }
}

HRMS/HRMS/Models/EmployeeProfessionalDeatils.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HRMS.Models
{
    public class EmployeeProfessionalDeatils
    {
        public string EmpId { get; set; }
        public string EmpDepartment { get; set; }

        public string EmpDesignation { get; set; }

        public string EmpReportingTo { get; set; }

        public string EmpExperience { get; set; }

        public DateTime EmpJobStartDate { get; set; }

        public DateTime EmpJobEndingDate { get; set; }



    }
}

HRMS/HRMS/Models/ErrorViewModel.cs
using System;

namespace HRMS.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

HRMS/HRMS/Models/Login.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HRMS.Models
{
    public class Login
    {
        public string EmpEmailId { get; set; }
        public string EmpPassword { get; set; }
    }
}

HRMS/HRMS/Controllers/DashBoardController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HRMS.Controllers
{
    public class DashBoardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult profile()
        {
            return View();
        }
    }
}

HRMS/HRMS/Controllers/EmployeeController.cs
using HRMS.Models;
using hrms_portal.models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Nancy.Json;
using Newtonsoft.Json;

namespace HRMS.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly IConfiguration configuration;

        public EmployeeController(IConfiguration configuration)
        {
            this.configuration = configuration;
        }
        public IActionResult AddEmployee()
        {
            var eid = new Repository(configuration);
            string id = eid.GetEmployeeId();

            return View("AddEmployee", id);
        }

        [HttpPost]
        public IActionResult AddEmployee(EmployeeDetails employeeDetail, EmployeeProfessionalDeatils employeeProfessionalDeatil, EmployeeEmergencyDetails employeeEmergencyDetail)
        {

            var eid = new Repository(configuration);
            //    eid.GetEmployeeId();
            //  var json = JsinC.Serialize(employeeFormModel);
            if (ModelState.IsValid)
            {
                var formData = new EmployeeFormModel
                {
                    EmployeeDetail = employeeDetail,
                    EmployeeEmergencyDetail = employeeEmergencyDetail,
                    EmployeeProfessionalDeatil = employeeProfessionalDeatil
                };

                var jsonData = JsonConvert.SerializeObject(formData);
                bool insert = eid.AddEmployee(jsonData);
                if (insert == true)
                    return View("Thanks", employeeDetail);
                else
                    return View("RegistrationError");
            }
            else
                return View("RegistrationError");
        }


        public IActionResult ShowEmployee()
        {
            var eid = new Repository(configuration);
            List<EmployeeDetails> list = eid.GetAllEmployee();

            return View("ShowEmployee", list);

        }

        //public IActionResult ShowEmployee(String str)
        //{
        //    //string connectionString = configuration["ConnectionStrings:DefaultConnection"];
        //    //con = new SqlConnection(connectionString);
        //    //con.Open();
        //    //int x = Repositery.Deleteproduct(id, con);
        //    //if (x > 0)
        //    //{
        //    //    productList = Repositery.GetAllProduct(con);
        //    //    return Content("deleted" + " " + productList.Count);
        //    //}
        //    //else
        //    //    return Content("deleted");
        //    //return View();
        //}

        public IActionResult UpdateEmployee(string id)
        {
            return View();
        }

        public IActionResult DeleteEmployee(string id)
        {
            return View();
        }
    }
}

HRMS/HRMS/Controllers/HomeController.cs
using HRMS.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace HRMS.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

HRMS/HRMS/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HRMS.Controllers
{
    public class LoginController : Controller
    {
        public IActionResult LoginPage()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login()
        {
            return View();
        }
    }
}

HRMS/HRMS/Views/Employee/RegistrationError.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "_Layout";
}

<h1>Sorry ! Plz try Again</h1>
<a  class="btn btn-primary" asp-action="AddEmployee" asp-controller="Employee">Back</a>

HRMS/HRMS/Views/Employee/ShowEmployee.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "_Layout";
}
@model List<EmployeeDetails>
<body>
    <main id="main" class="main">
        <div class="container mt-5">
            <div class="row d-flex justify-content-center align-items-center">
                <div class="col-md-12 ">
                    <form id="regForm" class="gradient-custom">
                        <h1 id="register" style="font-size: 300%; text-shadow: 2px 2px 8px #FF0000;"><b>All Employee</b></h1>
                        <section class="section dashboard">

                            <div class="row">

                                <!-- Left side columns -->
                                <div class="col-lg-12">
                                    <div class="row">
                                        <!-- Recent ADDED -->
                                        <div class="col-12 p-3">
                                            <div class="card recent-sales overflow-auto">
                                                <div class="card-body">
                                                    

                                                    <table class="table table-borderless datatable">
                                                        <thead>
                                                            <tr>
                                                                <th scope="col">Employee Id</th>
                                                                <th scope="col">Employee Name</th>
                                                                <th scope="col">Email Id</th>
                                                                <th scope="col">Employee Type</th>
                                                                <th scope="col">Mobilenumber</th>
                                                                <th scope="col">Gender</th>
                                                                <th scope="col">ADD</th>
                                                                <th scope="col">UPDATE</th>
                                                                <th scope="col">DELETE</th>

                                                            </tr>
                                                        </thead>
                                                        <tbody>
                                                            @foreach (var i in Model)
                                                             {
                                                                <tr>
                                                                    <td scope="row">@i.EmpId</td>
                                                                    <td scope="row">@i.EmpFullName</td>
                                                                    <td scope="row">@i.EmpEmail</td>
                                                                    <td scope="row">@i.Emptype</td>
                                                                    <td scope="row">@i.EmpMobilenumber</td>
                                                                    <td scope="row">@i.EmpGender</td>
                                                                
                                                                    <td>@Html.ActionLink("ADD","AddEmployee","Employee")</td>
                                                                    <td>@Html.ActionLink("UPDATE", "UpdateEmployee","Employee", new {id = @i.EmpId} )</td>
                                                                    <td>
                                                                        @Html.ActionLink("DELETE", "DeleteEmployee","Employee",new {id = @i.EmpId},
                                                                        new { onclick = "return confirm('Are sure wants to delete?');" })
                                                                    </td>
    
                                                                 </tr>
                                                             }
                                                        </tbody>
                                                    </table>
                                                </div>
                                            </div>
                                        </div>
                                    </div><!-- End Left side columns -->
                                </div>
                            </div>
                        </section>
                    </form>
                </div>
            </div>
        </div>
    </main>
</body>

HRMS/HRMS/Views/Employee/Thanks.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "_Layout";
}
@model EmployeeDetails

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Forms / Elements - NiceAdmin Bootstrap Template</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="assets/img/favicon.png" rel="icon">
    <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">


    <!-- Template Main CSS File -->
    <link href="~/css/AddEmployee.css" rel="stylesheet" />
    <script src="~/js/AddEmployee.js"></script>
    <!-- =======================================================
    * Template Name: NiceAdmin - v2.4.1
    * Template URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->
</head>
<body>

    <main id="main" class="main">
        <div class="container mt-5">
            <div class="row d-flex justify-content-center align-items-center">
                <div class="col-md-12 ">
                    <form id="regForm" class="gradient-custom">
                        <h1 id="register" style="font-size: 300%; text-shadow: 2px 2px 8px #FF0000;"><b>Employee Resigester Suceesfully</b></h1>

                        <div class="row">
                            <div class="col bx-font-size"><b>Employee Id</b></div>
                            <div class="col"><b>@Model.EmpId"</b></div>
                            <div class="w-100"></div>
                            <div class="col bx-font-size"><b>Employee Name</b></div>
                            <div class="col"><b>@Model.EmpFullName</b></div>
                            <div class="w-100"></div>
                            <div class="col bx-font-size"><b>Employee EmailId</b></div>
                            <div class="col"><b>@Model.EmpEmail</b></div>
                            <div class="w-100"></div>
                            <div class="col bx-font-size"><b>Employee password</b></div>
                            <div class="col"><b>@Model.EmpPassword</b></div>
                        </div>
                    </form>


                </div>
            </div>
        </div>
    </main>
</body>
</html>

HRMS/HRMS/Views/Home/Index.cshtml
@{
    Layout = "_Layout";
}
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1>HEllo</h1>
</div>

HRMS/HRMS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Dashboard - NiceAdmin Bootstrap Template</title>
    <meta content="" name="description">
    <meta content="" name="keywords">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css" integrity="sha384-xeJqLiuOvjUBq3iGOjvSQSIlwrpqjSHXpduPd6rQpuiM3f5/ijby8pCsnbu5S81n" crossorigin="anonymous">
    <!-- Favicons -->
    <link href="~/Icons/favicon.png" rel="icon">
    <link href="~/Icons/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/css/bootstrap-icons.css" rel="stylesheet">
    <link href="~/css/boxicons.min.css" rel="stylesheet">
    <link href="~/css/quill.snow.css" rel="stylesheet">
    <link href="~/css/quill.bubble.css" rel="stylesheet">
    <link href="~/css/remixicon.css" rel="stylesheet">
    <link href="~/css/style1.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="~/css/style.css" rel="stylesheet">

    <!-- =======================================================
    * Template Name: NiceAdmin - v2.4.1
    * Template URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->
</head>

<body>
    <main>
        <!-- ======= Header ======= -->
        <header id="header" class="header fixed-top d-flex align-items-center">

            <div class="d-flex align-items-center justify-content-between">
                <a href="index.html" class="logo d-flex align-items-center">
                    <img src="assets/img/logo.png" alt="">
                    <span class="d-none d-lg-block">NiceAdmin</span>
                </a>
                <i class="bi bi-list toggle-sidebar-btn"></i>
            </div><!-- End Logo -->

            <div class="search-bar">
                <form class="search-form d-flex align-items-center" method="POST" action="#">
                    <input type="text" name="query" placeholder="Search" title="Enter search keyword">
                    <button type="submit" title="Search"><i class="bi bi-search"></i></button>
                </form>
            </div><!-- End Search Bar -->

            <nav class="header-nav ms-auto">
                <ul class="d-flex align-items-center">

                    <li class="nav-item d-block d-lg-none">
                        <a class="nav-link nav-icon search-bar-toggle " href="#">
                            <i class="bi bi-search"></i>
                        </a>
                    </li><!-- End Search Icon-->

                    <li class="nav-item dropdown">




                    <li class="nav-item dropdown pe-3">

                        <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
                            <img src="assets/img/profile-img.jpg" alt="Profile" class="rounded-circle">
                            <span class="d-none d-md-block dropdown-toggle ps-2">K. Anderson</span>
                        </a><!-- End Profile Iamge Icon -->

                        <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
                            <li class="dropdown-header">
                                <h6>Kevin Anderson</h6>
                                <span>Web Designer</span>
                            </li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>

                            <li>
                                <a class="dropdown-item d-flex align-items-center" asp-action="profile" asp-controller="DashBoard">
                                    <i class="bi bi-person"></i>
                                    <span>My Profile</span>
                                </a>
                            </li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>

                            <li>
                                <a class="dropdown-item d-flex align-items-center" href="users-profile.html">
                                    <i class="bi bi-gear"></i>
                                    <span>Account Settings</span>
                                </a>
                            </li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>

                            <li>
                                <a class="dropdown-item d-flex align-items-center" href="pages-faq.html">
                                    <i class="bi bi-question-circle"></i>
                                    <span>Need Help?</span>
                                </a>
                            </li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>

                            <li>
                                <a class="dropdown-item d-flex align-items-center" asp-action="LoginPage" asp-controller="Login">
                                    <i class="bi bi-box-arrow-right"></i>
                                    <span>Sign Out</span>
                                </a>
                            </li>

                        </ul><!-- End Profile Dropdown Items -->
                    </li><!-- End Profile Nav -->

                </ul>
            </nav><!-- End Icons Navigation -->

        </header><!-- End Header -->
        <!-- ======= Sidebar ======= -->
        <aside id="sidebar" class="sidebar">

            <ul class="sidebar-nav" id="sidebar-nav">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="DashBoard" asp-action="Index">
                        <i class="bi bi-grid"></i>
                        <span>Home</span>
                    </a>
                </li><!-- End Dashboard Nav -->

                <li class="nav-item">
                    <a class="nav-link collapsed" data-bs-target="#components-nav" data-bs-toggle="collapse" href="#">
                        <i class="bi bi-menu-button-wide"></i><span>Me</span><i class="bi bi-chevron-down ms-auto"></i>
                    </a>
                    <ul id="components-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                        <li>
                            <a>
                                <i class="bi bi-circle"></i><span>Alerts</span>
                            </a>
                        </li>
                    </ul>
                </li><!-- End Components Nav -->

                <li class="nav-item">
                    <a class="nav-link collapsed" data-bs-target="#forms-nav" data-bs-toggle="collapse" href="#">
                        <i class="bi bi-journal-text"></i><span>Organisation</span><i class="bi bi-chevron-down ms-auto"></i>
                    </a>
                    <ul id="forms-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">

                        <li>
                            <a>
                                <i class="bi bi-circle"></i><span>Sumary</span>
                            </a>
                        </li>

                    </ul>
                </li><!-- End Forms Nav -->

                <li class="nav-item">
                    <a class="nav-link collapsed" data-bs-target="#tables-nav" data-bs-toggle="collapse" href="#">
                        <i class="bi bi-layout-text-window-reverse"></i><span>My Team</span><i class="bi bi-chevron-down ms-auto"></i>
                    </a>
                    <ul id="tables-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                        <li>
                            <a>
                                <i class="bi bi-circle"></i><span> Summary</span>
                            </a>
                        </li>
                    </ul>
                </li><!-- End Tables Nav -->

                <li class="nav-item">
                    <a class="nav-link collapsed" data-bs-target="#charts-nav" data-bs-toggle="collapse" href="#">
                        <i class="bi bi-bar-chart"></i><span>My Finance</span><i class="bi bi-chevron-down ms-auto"></i>
                    </a>
                    <ul id="charts-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                        <li>
                            <a>
                                <i class="bi bi-circle"></i><span>Chart.js</span>
                            </a>
                        </li>
                        <li>
                            <a>
                                <i class="bi bi-circle"></i><span>ApexCharts</span>
                            </a>
                        </li>
                        <li>
                            <a>
                                <i class="bi bi-circle"></i><span>ECharts</span>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link collapsed" data-bs-target="#chart-nav" data-bs-toggle="collapse" href="#">
                        <i class="bi bi-bar-chart"></i><span>Employee Management</span><i class="bi bi-chevron-down ms-auto"></i>
                    </a>
                    <ul id="chart-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                        <li>
                            <a asp-controller="Employee" asp-action="AddEmployee">
                                <i class="bi bi-circle"></i><span>Add Employee</span>
                            </a>
                        </li>
                        <li>
                            <a asp-controller="Employee" asp-action="ShowEmployee">
                                <i class="bi bi-circle"></i><span>All Employee Employee</span>
                            </a>
                        </li>
                    </ul>
                </li>
                <!-- End Charts Nav -->
            </ul>
        </aside><!-- End Sidebar-->


        <div class="">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>


    </main><!-- End #main -->
    <!-- ======= Footer ======= -->
    <footer id="footer" class="footer">
        <div class="copyright">
            &copy; Copyright <strong><span>NiceAdmin</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
            <!-- All the links in the footer should remain intact. -->
            <!-- You can delete the links only if you purchased the pro version. -->
            <!-- Licensing information: https://bootstrapmade.com/license/ -->
            <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/ -->
            Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
        </div>
    </footer><!-- End Footer -->

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <!-- Vendor JS Files -->
    <script src="~/assets/vendor/apexcharts/apexcharts.min.js"></script>
    <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/vendor/chart.js/chart.min.js"></script>
    <script src="~/assets/vendor/echarts/echarts.min.js"></script>
    <script src="~/assets/vendor/quill/quill.min.js"></script>
    <script src="~/assets/vendor/simple-datatables/simple-datatables.js"></script>
    <script src="~/assets/vendor/tinymce/tinymce.min.js"></script>
    <script src="~/assets/vendor/php-email-form/validate.js"></script>
    <!-- Template Main JS File -->
    <script src="~/assets/js/main.js"></script>
    @RenderSection("Scripts", required: false)
</body>

</html>